[package]
edition = "2021"
license = "Apache-2.0 OR MIT"
name = "sentry-tauri"
version = "0.0.1"

[dependencies]
sentry = {git = "https://github.com/getsentry/sentry-rust.git"}
sentry-rust-minidump = {git = "https://github.com/timfish/sentry-rust-minidump.git"}
serde = "1.0"
serde_json = "1.0"
tauri = "1.0.0-rc.12"
thiserror = "1.0"
