[package]
description = "An experimental Tauri Plugin for Sentry"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "sentry-tauri"
readme = "README.md"
repository = "https://github.com/timfish/sentry-tauri"
version = "0.2.0"

[dependencies]
base64 = "0.21"
sentry = "0.31"
sentry-rust-minidump = "0.6"
serde = "1"
tauri = "1"
thiserror = "1"
